apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-sa
  namespace: org-myorg
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: org-myorg:my-sa:edit
  namespace: org-myorg
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: my-sa
